[package]
name = "walrus"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive", "env"] }
directories = "5.0.1"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
tempfile = "3.12.0"
toml = "0.8.19"
walkdir = "2.5.0"

