[package]
name = "walrus"
version = "0.1.1"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.13", features = ["derive", "env"] }
ctrlc = { version = "3.4.5", features = ["termination"] }
directories = "5.0.1"
log = "0.4.22"
notify = "7.0.0"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { version = "1.0.204", features = ["derive"] }
simplelog = "0.12.2"
tempfile = "3.12.0"
toml = "0.8.19"
walkdir = "2.5.0"
