[package]
name = "walrus-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "walrus"
path = "src/main.rs"

[dependencies]
walrus-core = { path = "../walrus-core" }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
